title: SafeAI-Aus
description: Open-source Australian AI Risk & Safety Knowledge Base
theme: minima
markdown: kramdown

# --- GitHub Pages base URL settings ---
# If you publish as a *project site* (recommended), set:
#   url: "https://<your-username>.github.io"
#   baseurl: "/safeaiaus"
#
# If you publish as a *user/org site* (repo named <your-username>.github.io), set:
#   url: "https://<your-username>.github.io"
#   baseurl: ""
#
# We'll start blank so the site builds now; we can fill these after the repo is created.
url: "https://safeai-aus.github.io"
baseurl: ""

# Show the homepage in the header
header_pages:
  - about.md
  - index.md

# Note: minima doesn't read custom 'footer_content' from config by default.
# We can add a custom footer include later if you want a persistent license footer.

plugins:
  - jekyll-seo-tag
  - jekyll-feed
